#!/usr/bin/env python3
"""Find text that entered the corpus through the clipboard, not the model.

Endorphin's correction, 2026-08-04: some of this work was generated **outside
NovelAI** — Llama 2 via Replicate or Hyperbolic, where the temperature slider
goes to 5 rather than 2.5 — and then pasted back into a NovelAI story.

The export cannot see that. A pasted block carries `origin: user` or `edit`,
identical to something typed. So the schema's "human" is really *everything that
was not generated in this tab*: the author's own prose, source documents quoted
into Memory, and another model's output, all filed together.

That matters because `FINDINGS.md` is written under the turn-taking frame, and
the frame counts human turns.

    python3 analysis/pasted.py data/stories_meta.jsonl --report analysis/PASTED.md

This runs off `data/stories_meta.jsonl` alone, so it works without the ~1 GB
mirror. It is a screen, not a classifier: it cannot separate another model's
output from a long quotation or the author's own typing.
"""

import argparse
import collections
import json
import pathlib
import statistics


def load(path):
    return [json.loads(line) for line in open(path)]


def screen(rows, min_human=20000, min_ratio=1.5):
    """Stories whose 'human' text dwarfs what the model produced in-tab."""
    out = []
    for r in rows:
        ai, human = r["live_ai_chars"], r["human_chars"]
        if human >= min_human and human / (ai + 1) >= min_ratio:
            out.append((human / (ai + 1), r))
    return sorted(out, key=lambda x: -x[0])


def report(rows, flagged, out):
    human_all = sum(r["human_chars"] for r in rows)
    human_flag = sum(r["human_chars"] for _, r in flagged)
    silent = [r for _, r in flagged if r["live_ai_chars"] == 0]

    def blocksize(rs):
        sizes = [r["human_chars"] / max(1, r["blocks_by_origin"].get("user", 0)
                                        + r["blocks_by_origin"].get("edit", 0))
                 for r in rs if r["human_chars"]]
        return statistics.median(sizes) if sizes else 0

    flagged_rows = [r for _, r in flagged]
    rest = [r for r in rows if r not in flagged_rows]

    L = [
        "# Pasted — text that did not come from the model in this tab", "",
        "Generated by `analysis/pasted.py`.", "",
        f"- **{len(flagged)} of {len(rows)} stories** "
        f"({100 * len(flagged) / len(rows):.0f}%) hold more 'human' text than "
        "model text, by at least half again, on at least 20,000 characters.",
        f"- **{len(silent)}** of those produced **no in-tab generation at all** "
        "(`live_ai_chars` = 0).",
        f"- Together they carry **{human_flag:,} characters** — "
        f"**{100 * human_flag / human_all:.0f}% of all 'human' text in the "
        "corpus.**", "",
        "## Why this is not just long typing", "",
        f"Median human block in the flagged set: **{blocksize(flagged_rows):,.0f} "
        f"characters**. In the rest of the corpus: "
        f"**{blocksize(rest):,.0f} characters**.", "",
        "`FINDINGS.md`'s central structural claim — that the author's turn is a",
        "**cue**, median 55 characters, not an edit — is about the *shape* of the",
        "typical turn, and these blocks are nowhere near it. They sit far out in",
        "the tail. **The cue finding survives.** What does not survive is any",
        "claim built on human/model character *ratios*, because a fifth of the",
        "human side arrived by clipboard.", "",
        "## What is actually in here", "",
        "Three different things the schema cannot tell apart:", "",
        "1. **Another model's output.** Endorphin used Llama 2 through Replicate",
        "   or Hyperbolic for some of the Pynchon × Tingle and Sydney Bing work,",
        "   at temperatures up to 5. `Llama2 explicates Hebrew(ish)?` is the",
        "   clearest specimen: 10 blocks, **0** model characters, **60,950**",
        "   'human' characters.",
        "2. **Source documents.** The US Army monograph on dispensational",
        "   pre-millennialism, a Guardian obituary, the opening of *Bleeding",
        "   Edge* — all quoted in wholesale.",
        "3. **The author's own writing**, which is the only one the frame wants.",
        "",
        "## The `model` field is not the generator", "",
        "`powered by LLAMA 3.1 - 3 - 403B BASE   Counterfactual interview - JD",
        "Vance` records `kayra-v1` in its settings, because that is what the",
        "NovelAI tab was set to. The title says what actually produced the text.",
        "**Treat `model` as *what the client was configured for*, not *what wrote",
        "this*.**", "",
        "## The 2.5 ceiling is not universal", "",
    ]
    hot = [r for r in rows if (r["temperature"] or 0) > 2.5]
    bym = collections.Counter(r["model"] for r in hot)
    L.append(f"{len(hot)} stories carry a temperature above 2.5: "
             + ", ".join(f"`{m}` ×{n}" for m, n in bym.most_common()) + ".")
    L += ["",
          "`READINGS.md` §III and `analysis/SWEEPS.md` both treat 2.5 as the",
          "slider's maximum. That held for the Kayra era. It does not hold",
          "everywhere, and it never held for the work done off-platform.", "",
          "## Worst offenders", "",
          "| edited | model field | blocks | model chars | 'human' chars | title |",
          "|---|---|---:|---:|---:|---|"]
    import datetime
    for _, r in flagged[:20]:
        d = datetime.datetime.fromtimestamp(
            r["last_updated_at"], datetime.timezone.utc).strftime("%Y-%m")
        L.append(f"| {d} | {r['model']} | {r['n_blocks']} | "
                 f"{r['live_ai_chars']:,} | {r['human_chars']:,} | "
                 f"{r['title'][:44]} |")
    out.write_text("\n".join(L) + "\n", encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("meta")
    ap.add_argument("--report", type=pathlib.Path)
    args = ap.parse_args()
    rows = load(args.meta)
    flagged = screen(rows)
    if args.report:
        report(rows, flagged, args.report)
        print(f"{len(flagged)} flagged -> {args.report}")
    else:
        for ratio, r in flagged[:20]:
            print(f"{ratio:10.1f}  {r['human_chars']:8}  {r['title'][:50]}")


if __name__ == "__main__":
    main()
