#!/usr/bin/env python3
"""If the rejected text does not predict rejection, what does?

`learnable.py` finds no within-pair signal: you cannot tell from a rejected
generation that it was the rejected one. That makes the interesting variable
the *process* rather than the text -- how many times you re-rolled before
accepting, and how often no generation was acceptable at all.

Reads blocks.jsonl and stories.jsonl; writes STOPPING.md.
"""

import argparse
import json
import pathlib
import statistics
from collections import Counter, defaultdict


def stories_from_blocks(path):
    cur_id, buf = None, []
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            b = json.loads(line)
            if b["remote_id"] != cur_id:
                if cur_id is not None:
                    yield cur_id, buf
                cur_id, buf = b["remote_id"], []
            buf.append(b)
    if cur_id is not None:
        yield cur_id, buf


def classify_branches(blocks_path, meta):
    """One record per branch point: how many AI attempts, and how it resolved."""
    recs = []
    for rid, blocks in stories_from_blocks(blocks_path):
        m = meta.get(rid)
        if not m:
            continue
        by_idx = {b["block_index"]: b for b in blocks}
        for b in blocks:
            succ = [by_idx[i] for i in (b["next_blocks"] or []) if i in by_idx]
            if len(succ) < 2:
                continue
            ai = [s for s in succ if s["origin"] == "ai"]
            if not ai:
                continue
            live = [s for s in succ if s["live"]]
            if not live:
                continue  # whole subtree abandoned; no resolution to read
            winner = live[0]
            recs.append(
                {
                    "model": m["model"],
                    "temperature": m["temperature"],
                    "ai_attempts": len(ai),
                    "resolution": "accepted_generation"
                    if winner["origin"] == "ai"
                    else "human_wrote_it",
                    "winner_origin": winner["origin"],
                }
            )
    return recs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out_dir", type=pathlib.Path)
    ap.add_argument("--report", type=pathlib.Path, default=None)
    args = ap.parse_args()

    meta = {}
    with (args.out_dir / "stories.jsonl").open(encoding="utf-8") as fh:
        for line in fh:
            r = json.loads(line)
            if r.get("remote_id"):
                meta[r["remote_id"]] = r

    recs = classify_branches(args.out_dir / "blocks.jsonl", meta)
    n = len(recs)
    out = ["# What ends a retry run?", "", "Generated by `analysis/stopping.py`.", ""]
    out.append(
        f"**{n:,}** branch points where at least one generation was re-rolled "
        "and the branch resolved.\n"
    )

    res = Counter(r["resolution"] for r in recs)
    out.append("| resolution | branches | share |")
    out.append("|---|---:|---:|")
    for k, v in res.most_common():
        out.append(f"| {k.replace('_', ' ')} | {v:,} | {100 * v / n:.1f}% |")
    out.append("")
    took = res["human_wrote_it"]
    out.append(
        f"**{100 * took / n:.0f}%** of re-roll events end with you writing it "
        "yourself rather than accepting any generation. That is the single "
        "largest category of 'rejection' in the corpus, and it is invisible to a "
        "chosen/rejected pair set, which by construction only sees the branches "
        "where a generation eventually won.\n"
    )

    out.append("## How many re-rolls before you stop\n")
    acc = [r["ai_attempts"] for r in recs if r["resolution"] == "accepted_generation"]
    hum = [r["ai_attempts"] for r in recs if r["resolution"] == "human_wrote_it"]
    out.append("| outcome | branches | median AI attempts | mean | p90 | max |")
    out.append("|---|---:|---:|---:|---:|---:|")
    for label, v in (("accepted a generation", acc), ("wrote it yourself", hum)):
        if not v:
            continue
        s = sorted(v)
        p90 = s[min(len(s) - 1, int(round(0.9 * (len(s) - 1))))]
        out.append(
            f"| {label} | {len(v):,} | {statistics.median(v):.0f} | "
            f"{statistics.fmean(v):.2f} | {p90} | {max(v)} |"
        )
    out.append("")

    out.append("## Acceptance by attempt number\n")
    out.append(
        "Of branches that reached at least *k* AI attempts, the share that "
        "stopped at exactly *k* with a generation accepted. A flat column means "
        "each re-roll is an independent coin flip; a rising one means you settle "
        "as the run goes on.\n"
    )
    out.append("| attempts k | branches reaching k | stopped at k with a generation | wrote it yourself at k |")
    out.append("|---|---:|---:|---:|")
    for k in range(1, 9):
        at_least = [r for r in recs if r["ai_attempts"] >= k]
        if len(at_least) < 40:
            break
        exact = [r for r in at_least if r["ai_attempts"] == k]
        a = sum(1 for r in exact if r["resolution"] == "accepted_generation")
        h = sum(1 for r in exact if r["resolution"] == "human_wrote_it")
        out.append(
            f"| {k} | {len(at_least):,} | {100 * a / len(at_least):.1f}% | "
            f"{100 * h / len(at_least):.1f}% |"
        )
    out.append("")

    out.append("## By model\n")
    out.append("| model | branches | wrote it yourself | median attempts when accepted |")
    out.append("|---|---:|---:|---:|")
    for mdl, c in Counter(r["model"] for r in recs).most_common():
        if c < 200:
            continue
        sub = [r for r in recs if r["model"] == mdl]
        h = sum(1 for r in sub if r["resolution"] == "human_wrote_it")
        a = [r["ai_attempts"] for r in sub if r["resolution"] == "accepted_generation"]
        out.append(
            f"| `{mdl}` | {len(sub):,} | {100 * h / len(sub):.1f}% | "
            f"{statistics.median(a):.0f} |" if a else
            f"| `{mdl}` | {len(sub):,} | {100 * h / len(sub):.1f}% | - |"
        )
    out.append("")

    dest = args.report or (args.out_dir / "STOPPING.md")
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
