#!/usr/bin/env python3
"""Find the sweep procedure in the fork structure.

`FINDINGS.md` and `READINGS.md` §III both argue that the temperature sweeps were
a *designed procedure* — pick a preset, work a register, step the temperature up,
note where it breaks — and both argue it from the distribution of settings across
stories. That is indirect. This finds the procedure as an artifact instead.

A sweep leaves a signature: several forks of one story, all last touched on the
same day, `max_length` held constant, temperature varied. Duplicating a story in
NovelAI copies its whole branch history, so each fork preserves one run at one
setting. The duplication that `analysis/` has spent three sessions correcting for
is not a filing habit — **it is the experiment.**

    python3 analysis/sweeps.py data/stories_meta.jsonl --report analysis/SWEEPS.md

Grouping is by title stem with the `(n)` suffix stripped, which is deliberately
crude: it will merge genuinely separate stories that share a name, and it cannot
see sweeps whose forks were renamed. Treat the counts as a floor.
"""

import argparse
import collections
import datetime
import json
import re
import statistics


def load(path):
    for line in open(path):
        r = json.loads(line)
        yield {
            "stem": re.sub(r"\s*\(\d+\)$", "", r["title"]).lower(),
            "day": datetime.datetime.fromtimestamp(
                r["last_updated_at"], datetime.timezone.utc).date(),
            "model": r["model"],
            "preset": r["preset"],
            "temp": r["temperature"],
            "max_length": r["max_length"],
            "blocks": r["n_blocks"],
            "enabled": tuple(r["sampler_order_enabled"]),
        }


def clusters(rows, min_forks=3, min_temps=2):
    """Same story, same day, several forks, more than one temperature."""
    g = collections.defaultdict(list)
    for r in rows:
        g[(r["stem"], r["day"])].append(r)
    out = []
    for (stem, day), forks in g.items():
        if len(forks) < min_forks:
            continue
        if len({f["temp"] for f in forks}) < min_temps:
            continue
        out.append((stem, day, sorted(forks, key=lambda f: f["temp"])))
    return sorted(out, key=lambda c: (-len(c[2]), c[1]))


def report(rows, cs, out):
    total_forks = sum(len(c[2]) for c in cs)
    stems = {c[0] for c in cs}
    held = sum(1 for _, _, f in cs if len({x["max_length"] for x in f}) == 1)
    onemodel = sum(1 for _, _, f in cs if len({x["model"] for x in f}) == 1)
    ceiling = sum(1 for _, _, f in cs if max(x["temp"] for x in f) == 2.5)
    onepreset = sum(1 for _, _, f in cs if len({x["preset"] for x in f}) == 1)
    mixed_forks = sum(len(f) for _, _, f in cs if len({x["preset"] for x in f}) > 1)

    L = ["# Sweeps — the procedure, recovered from the fork structure", "",
         "Generated by `analysis/sweeps.py`. A sweep is taken to be **three or more",
         "forks of one story, last touched on the same day, at two or more",
         "temperatures**.", "",
         f"- **{len(cs)} sweep clusters**, covering **{total_forks} forks** "
         f"of {len(rows)} stories ({100 * total_forks / len(rows):.0f}%) "
         f"across {len(stems)} title stems.",
         f"- `max_length` held constant within the cluster: "
         f"**{held}/{len(cs)}** ({100 * held / len(cs):.0f}%).",
         f"- A single model within the cluster: **{onemodel}/{len(cs)}** "
         f"({100 * onemodel / len(cs):.0f}%).",
         f"- Cluster tops out at exactly **2.5**, the slider's maximum: "
         f"**{ceiling}/{len(cs)}** ({100 * ceiling / len(cs):.0f}%).",
         f"- **A single preset within the cluster: {onepreset}/{len(cs)}** "
         f"({100 * onepreset / len(cs):.0f}%) — the preset moves in "
         f"{100 * (len(cs) - onepreset) / len(cs):.0f}% of them, covering "
         f"{mixed_forks}/{total_forks} swept forks "
         f"({100 * mixed_forks / total_forks:.0f}%).", "",
         "## What this settles",
         "",
         "The duplication warning in `CLAUDE.md` — *never group by story id, raw",
         "counts inflate 5×* — is still correct for counting. But the reason for the",
         "duplication is now visible: **the forks are the instrument.** Each copy",
         "preserves one run at one setting, which is why they cluster on single days",
         "with a held `max_length` and a moving temperature.",
         "",
         "§III argues the sweep procedure from the distribution of settings across",
         "stories. This is the same procedure as a within-document controlled",
         "experiment, several hundred times over.",
         "",
         "## What it does not settle: these are not temperature sweeps",
         "",
         "`max_length` is held in half the clusters and the model in 83% of them, but",
         f"**the preset is held in only {100 * onepreset / len(cs):.0f}%**. "
         f"{100 * mixed_forks / total_forks:.0f}% of swept forks sit in a cluster",
         "where preset and temperature moved together. Calling the ladder a",
         "temperature ladder was the reading available when this script only looked",
         "at `temperature`.",
         "",
         "`analysis/MYTHS.md` shows why that matters. In `Mythmaker - Working Copy`,",
         "76 forks of one story on one model, temperature 2.5 produces 0.61%",
         "non-words under `freshcoffeek`, 0.75% under `asper` and 7.18% under",
         "`writersdaemon` — an eleven-fold range at the *same* value of the dial,",
         "ordered by whether a hard `top_k` sits after temperature in the sampler",
         "order. **A temperature is not a setting in this corpus unless the preset",
         "is quoted with it.** The clusters below are preset × temperature designs,",
         "and reading them as one-dimensional is what `CLAUDE.md`'s standing note",
         "about settings moving with model choice warns against, one level down.",
         "",
         "## Largest clusters", "",
         "| day | forks | story | temperatures | max_length | model |",
         "|---|---:|---|---|---|---|"]
    for stem, day, forks in cs[:25]:
        temps = ", ".join(f"{f['temp']:g}" for f in forks)
        mls = "/".join(str(x) for x in sorted({f["max_length"] for f in forks}))
        models = "/".join(sorted({f["model"] for f in forks}))
        L.append(f"| {day} | {len(forks)} | {stem[:40]} | {temps[:70]} "
                 f"| {mls} | {models[:26]} |")

    L += ["", "## Where the ladders stop", ""]
    tops = collections.Counter(max(f["temp"] for f in forks) for _, _, forks in cs)
    L.append("| top temperature | clusters |")
    L.append("|---:|---:|")
    for t, n in sorted(tops.items(), reverse=True)[:12]:
        L.append(f"| {t:g} | {n} |")
    L += ["",
          "2.5 is where NovelAI's slider stops, not where language does — the point",
          "`READINGS.md` §III makes about the corpus's outer boundary being an",
          "interface constraint. The clusters that stop short of it are the ones",
          "worth reading: they stopped because something was found, not because the",
          "widget ran out.", ""]

    spans = [statistics.median([f["blocks"] for f in forks]) for _, _, forks in cs]
    L.append(f"Median fork size within a cluster: **{statistics.median(spans):.0f} "
             f"blocks**.")
    out.write_text("\n".join(L) + "\n", encoding="utf-8")


def main():
    import pathlib
    ap = argparse.ArgumentParser()
    ap.add_argument("meta", help="data/stories_meta.jsonl")
    ap.add_argument("--report", type=pathlib.Path)
    args = ap.parse_args()
    rows = list(load(args.meta))
    cs = clusters(rows)
    if args.report:
        report(rows, cs, args.report)
        print(f"{len(cs)} clusters, {sum(len(c[2]) for c in cs)} forks "
              f"-> {args.report}")
    else:
        for stem, day, forks in cs[:20]:
            print(day, len(forks), stem, sorted(f["temp"] for f in forks))


if __name__ == "__main__":
    main()
