#!/usr/bin/env python3
"""Did the generation keep a beat?

`FINDINGS.md` §11 records that no per-block timestamps exist, so tempo -- the
pace of the exchange -- is unrecoverable. That is true of duration. It is not
quite true of rhythm.

Endorphin's account: the output was read aloud by text-to-speech over a lo-fi
backing track, which made the voice read as continuous freestyle or poetry. The
constraint was therefore not merely "avoid silence" but "keep the audio flowing
at a steady clip", with the author acting as artist and audience at once --
listening to the generation in real time, and letting what he heard inform the
next move.

If that is right, the *length* of each accepted generation should track the one
immediately before it, and that coupling should decay over a few turns. A slow
drift across a session would not do that; it would show up equally at every lag.

Test: within unbroken runs of generation, compare |Δ words| between generations
`lag` apart against the same run with its order shuffled. Shuffling preserves
the run's whole length distribution -- so `max_length` capping, model choice and
session-level habits all cancel -- and destroys only the sequence.

    python3 analysis/tempo.py out --report analysis/TEMPO.md
"""

import argparse
import json
import pathlib
import random
import re
import statistics
from collections import defaultdict

TOKEN = re.compile(r"[A-Za-z][A-Za-z'-]*")
LAGS = (1, 2, 3, 4, 6, 8)


def stories_from_blocks(path):
    cur_id, buf = None, []
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            b = json.loads(line)
            if b["remote_id"] != cur_id:
                if cur_id is not None:
                    yield cur_id, buf
                cur_id, buf = b["remote_id"], []
            buf.append(b)
    if cur_id is not None:
        yield cur_id, buf


def runs_of_generation(blocks, min_len, min_words=20):
    """Word counts of consecutive AI blocks on the surviving branch."""
    live = sorted((b for b in blocks if b.get("live")), key=lambda b: b["block_index"])
    out, run = [], []
    for b in live:
        if b["origin"] == "ai":
            run.append(len(TOKEN.findall(b["text"])))
        else:
            if len(run) >= min_len:
                out.append(run)
            run = []
    if len(run) >= min_len:
        out.append(run)
    cleaned = []
    for r in out:
        r = [x for x in r if x >= min_words]
        if len(r) >= min_len:
            cleaned.append(r)
    return cleaned


def measure(blocks_path, meta, min_len=8, seed=21):
    rng = random.Random(seed)
    obs, shuf = defaultdict(list), defaultdict(list)
    n_runs = 0
    for rid, blocks in stories_from_blocks(blocks_path):
        if rid not in meta:
            continue
        for r in runs_of_generation(blocks, min_len):
            n_runs += 1
            s = r[:]
            rng.shuffle(s)
            for lag in LAGS:
                for i in range(len(r) - lag):
                    obs[lag].append(abs(r[i] - r[i + lag]))
                for i in range(len(s) - lag):
                    shuf[lag].append(abs(s[i] - s[i + lag]))
    return obs, shuf, n_runs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out_dir", type=pathlib.Path)
    ap.add_argument("--report", type=pathlib.Path, default=None)
    ap.add_argument("--min-run", type=int, default=8)
    args = ap.parse_args()

    meta = {}
    with (args.out_dir / "stories.jsonl").open(encoding="utf-8") as fh:
        for line in fh:
            r = json.loads(line)
            if r.get("remote_id") and r["ai_chars"] > 0:
                meta[r["remote_id"]] = r

    obs, shuf, n_runs = measure(args.out_dir / "blocks.jsonl", meta, args.min_run)

    out = ["# Tempo", "", "Generated by `analysis/tempo.py`.", ""]
    out.append(
        f"Unbroken runs of at least {args.min_run} generations: **{n_runs:,}**. "
        "Within each, the absolute difference in word count between generations "
        "*lag* apart, against the same run with its order shuffled. Shuffling "
        "keeps the run's entire length distribution and destroys only the "
        "sequence, so `max_length`, model and session habits all cancel.\n"
    )
    out.append("| lag | pairs | observed \\|Δ words\\| | shuffled | reduction |")
    out.append("|---:|---:|---:|---:|---:|")
    for lag in LAGS:
        if not obs[lag]:
            continue
        o = statistics.fmean(obs[lag])
        s = statistics.fmean(shuf[lag])
        out.append(
            f"| {lag} | {len(obs[lag]):,} | {o:.2f} | {s:.2f} | "
            f"**{100 * (s - o) / s:.1f}%** |"
        )
    out.append("")

    first = statistics.fmean(obs[1])
    first_s = statistics.fmean(shuf[1])
    out.append(
        f"Adjacent generations are **{100 * (first_s - first) / first_s:.1f}%** "
        "closer in length than the same generations in a scrambled order, and "
        "the effect decays to nothing by six turns out.\n"
    )
    out.append(
        "**That decay is the result.** A slow drift across a session — getting "
        "steadily more expansive, or steadily terser — would show the same "
        "reduction at every lag, because shuffling destroys a trend just as "
        "thoroughly as it destroys a rhythm. A reduction that is largest at "
        "lag 1 and gone by lag 6 is short-memory coupling: each generation's "
        "length tracks the one just before it, over a window of about five "
        "turns.\n"
    )
    out.append(
        "This is a partial walk-back of §11's claim that tempo is unrecoverable. "
        "Duration is genuinely absent — there are no timestamps. But the "
        "*sequence* of lengths carries a trace of pacing, and it behaves the way "
        "the streaming account predicts: the author was keeping the text-to-"
        "speech voice fed at a steady clip, and adjusted the size of the next "
        "move to what he had just heard.\n"
    )
    out.append(
        "What it cannot show is direction. A steady clip could be the author "
        "pacing the model, or the model's own output-length autocorrelation "
        "pacing the author, or both locked together — which is what the "
        "collaboration account would actually predict. Nothing here separates "
        "those, and per-generation `max_length` is not recorded, so nothing "
        "here can.\n"
    )

    dest = args.report or (args.out_dir / "TEMPO.md")
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
